config/routes.rb
RailsDb::Engine.routes.draw do
  root :to => 'dashboard#index'

  resources :tables, :only => [:index, :show] do
    get 'data'
    get 'csv'
    get 'truncate'
    get 'destroy' # to handle opens in new window (GET)
    get 'edit'    # to handle opens in new window (GET)
    put 'update'  # to handle opens in new window (GET)
    get 'xlsx'
    get 'new'
    post 'create'
  end

  get '/sql' => 'sql#index', as: :sql
  get '/import' => 'sql#import', as: :sql_import

  post '/execute' => 'sql#execute', as: :sql_execute
  post '/sql-csv' => 'sql#csv', as: :sql_csv
  post '/sql-xls' => 'sql#xls', as: :sql_xls
  post '/import-start' => 'sql#import_start', as: :sql_start_import

  get '/data-table' => 'dashboard#data_table', as: :data_table
  get '/standalone' => 'dashboard#standalone', as: :standalone
end

if RailsDb.automatic_routes_mount
  Rails.application.routes.draw do
    mount_rails_db_routes
  end
end

app/controllers/rails_db/application_controller.rb
module RailsDb
  class ApplicationController < ActionController::Base
    helper :all
    helper_method :per_page

    before_action :verify_access
    before_action :set_abstract_model_class

    if RailsDb.http_basic_authentication_enabled
      http_basic_authenticate_with name: RailsDb.http_basic_authentication_user_name,
                                   password: RailsDb.http_basic_authentication_password
    end

    private

    def verify_access
      result = RailsDb.verify_access_proc.call(self)
      redirect_to('/', error: 'Access Denied', status: 401) unless result
    end

    def per_page
      params[:per_page] || session[:per_page]
    end

    def set_abstract_model_class
      return unless params[:abstract_model_class].present?

      if (found = RailsDb.available_abstract_model_classes.find { |klass| klass.name == params[:abstract_model_class] })
        RailsDb.abstract_model_class = found
      end
    end
  end
end

app/controllers/rails_db/dashboard_controller.rb
module RailsDb
  class DashboardController < RailsDb::ApplicationController

    def index
    end

  end
end

app/controllers/rails_db/sql_controller.rb
module RailsDb
  class SqlController < RailsDb::ApplicationController
    before_action :load_query, only: [:index, :execute, :csv, :xls]

    def index
    end

    def execute
      render :index
    end

    def csv
      send_data(@sql_query.to_csv, type: 'text/csv; charset=utf-8; header=present', filename: 'results.csv')
    end

    def xls
      render xlsx: 'xls', filename: 'results.xlsx'
    end

    def import
    end

    def import_start
      @importer = SqlImport.new(params[:file])
      result    = @importer.import
      if result.ok?
        flash[:notice] = 'File was successfully imported'
      else
        flash[:alert] = "Error occurred during import: #{result.error.message}"
      end
      render :import
    end

    private

    def load_query
      @sql       = "#{params[:sql]}".strip
      @sql_query = RailsDb::SqlQuery.new(@sql).execute
    end

  end
end

app/controllers/rails_db/tables_controller.rb
module RailsDb
  class TablesController < RailsDb::ApplicationController
    LOAD_TABLE_ACTIONS = [:show, :data, :csv, :truncate, :destroy, :edit, :update, :xlsx, :new, :create]

    before_action :find_table, only: LOAD_TABLE_ACTIONS

    def index
      @tables = RailsDb::Database.accessible_tables
    end

    def show
    end

    def new
      @record = model.new
    end

    def create
      unless RailsDb.sandbox
        @record = model.new(record_attributes)
        @record.save!
      end

      build_search
      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    def data
      session[:per_page] = per_page
      build_search
      respond_to do |page|
        page.html {}
        page.js {}
      end
    end

    def csv
      send_data(@table.to_csv, type: 'text/csv; charset=utf-8; header=present', filename: "#{@table.name}.csv")
    end

    def xlsx
      if defined? Axlsx
        render xlsx: 'table', filename: "#{@table.name}.xlsx"
      else
        raise 'RailsDb could not find Axlsx, please add it to your Gemfile: "gem \'caxlsx_rails\'"'
      end
    end

    def truncate
      unless RailsDb.sandbox
        @table.truncate
      end
      render :data
    end

    def destroy
      build_search

      unless RailsDb.sandbox
        @table.delete(params[:pk_id])
      end

      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    def edit
      @record = @table.as_model.find(params[:pk_id])
      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    def update
      @record = @table.as_model.find(params[:pk_id])

      unless RailsDb.sandbox
        @record.update(record_attributes)
      end

      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    private

    def build_search
      if Rails::VERSION::MAJOR >= 5
        search_params = params.dup.permit!.to_h.with_indifferent_access
      else
        search_params = params
      end
      @q       = model.ransack(search_params[:q])
      @sql     = @q.result.page(params[:page]).per(per_page).to_sql
      @records = @q.result.page(params[:page]).per(per_page)
      @q.build_condition if @q.conditions.empty?
      @q.build_sort      if @q.sorts.empty?
    end

    def model
      @model ||= @table.as_model
    end

    def record_attributes
      params[:record].permit!
    end

    def find_table
      @table ||= RailsDb::Table.new(params[:id] || params[:table_id])
    end

  end
end

app/helpers/rails_db/application_helper.rb
module RailsDb
  module ApplicationHelper

    def rails_db
      super
    rescue NameError
      guess_name(request.path.split('/').reject(&:blank?))
    end

    # in case engine was added in namespace
    def guess_name(sections)
      if sections.size > 1
        sections[-1] = 'rails_db'
        variable     = sections.join("_")
        result       = eval(variable)
      end
    rescue NameError
      sections.delete_at(-2)
      guess_name(sections)
    end

    def rails_db_tables
      RailsDb::Database.accessible_tables
    end

    def link_to_add_fields(name, f, type)
      new_object = f.object.send "build_#{type}"
      id = "new_#{type}"
      fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
        render(type.to_s + "_fields", f: builder)
      end
      link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end

    def sidebar_classes
      if show_sidebar?
        'large-3 large-pull-9 columns'
      else
        'large-3 large-pull-9 columns hide'
      end
    end

    def main_content_classes
      if show_sidebar?
        'large-9 push-3 columns collapsed'
      else
        'large-12 push-0 columns expanded'
      end
    end

    def show_sidebar?
      return true if controller_name == 'dashboard' && action_name == 'index'
      cookies['sidebar_hidden'] != 'true'
    end

    def title(str)
      content_for :title do
        raw("#{str}"[0].upcase + "#{str}"[1..-1])
      end
    end

    def fa_icon(icon_name)
      %{<i class="fa fa-#{icon_name}"></i>}.html_safe
    end

    def db_hint_options
      result = {}
      RailsDb::Database.accessible_tables.each do |table_name|
        result[table_name] = RailsDb::Table.new(table_name).columns.inject([]) {|res, e| res << e.name; res }
      end
      result
    end

    def params_to_hash(p)
      if p.respond_to?(:to_unsafe_h)
        p.to_unsafe_h
      else
        p
      end
    end

    def insert_css_file(file)
      if using_sprockets?
        # For Sprockets, use the asset pipeline
        # Remove .css extension and use the file path as-is for asset pipeline
        asset_name = file.gsub('.css', '')
        stylesheet_link_tag asset_name, media: "all"
      else
        # For Propshaft/Rails 8 compatibility - inline the CSS
        css_path = File.expand_path(File.dirname(__FILE__) + "/../../assets/stylesheets/#{file}")
        if File.exist?(css_path)
          raw "<style>#{File.read(css_path)}</style>"
        else
          ""
        end
      end
    end

    def insert_js_file(file)
      if using_sprockets?
        # For Sprockets, use the asset pipeline
        # Remove .js extension and use the file path as-is for asset pipeline
        asset_name = file.gsub('.js', '')
        javascript_include_tag asset_name
      else
        # For Propshaft/Rails 8 compatibility - inline the JavaScript
        js_path = File.expand_path(File.dirname(__FILE__) + "/../../assets/javascripts/#{file}")
        if File.exist?(js_path)
          raw "<script>#{File.read(js_path)}</script>"
        else
          ""
        end
      end
    end

    private

    def using_sprockets?
      # Check if sprockets-rails is available and being used
      return false unless defined?(Sprockets)
      
      # Check if Rails.application.assets is a Sprockets environment
      Rails.application.assets.is_a?(Sprockets::Environment) ||
      Rails.application.assets.is_a?(Sprockets::Index)
    rescue
      # If anything fails, assume we're not using Sprockets
      false
    end
  end
end

app/helpers/rails_db/flash_messages_helper.rb
module RailsDb
  module FlashMessagesHelper
    # <div class="alert-box [success alert secondary]">
    #   This is an alert box.
    #   <a href="" class="close">&times;</a>
    # </div>
    DEFAULT_KEY_MATCHING = {
      :alert     => :alert,
      :notice    => :success,
      :info      => :info,
      :secondary => :secondary,
      :success   => :success,
      :error     => :alert,
      :warning   => :warning
    }
    def display_flash_messages(key_matching = {})
      key_matching = DEFAULT_KEY_MATCHING.merge(key_matching)
      key_matching.default = :standard

      result = capture do
        flash.each do |key, value|
          alert_class = key_matching[key.to_sym]
          concat alert_box(value, alert_class)
        end
      end
      flash.clear
      result
    end

  private

    def alert_box(value, alert_class)
      content_tag :div, data: { alert: '' }, class: "alert-box #{alert_class}" do
        concat value
        concat close_link
      end
    end

    def close_link
      link_to("&times;".html_safe, '#', class: :close)
    end

  end
end

app/helpers/rails_db/rails_db_data_table_helper.rb
module RailsDb
  module RailsDbDataTableHelper
    # TODO check styles
    STYLES = {
      default: {
        table: 'table',
        tr: 'table_tr',
        th: 'table_th',
        td: 'table_td',
        thead: 'table_thead',
        tfoot: 'table_tfoot'
      },
      bootstrap: {
        table: 'table table-bordered table-striped table-hover',
        tr: 'table_tr',
        th: 'table_th',
        td: 'table_td',
        thead: 'table_thead',
        tfoot: 'table_tfoot'
      },
      foundation: {
        table: 'table',
        tr: 'table_tr',
        th: 'table_th',
        td: 'table_td',
        thead: 'table_thead',
        tfoot: 'table_tfoot'
      }
    }

    def rails_db_data_table(table_name, options = {})
      options.reverse_merge!(
        style: :default,
        header: true,
        footer: false,
        columns: [],
        limit: nil,
        order_by: nil,
        order: :asc
      )
      table = RailsDb::Table.new(table_name)
        .limit(options[:limit])
        .order_by(options[:order_by])
        .select(options[:columns])
        .order(options[:order])

      render '/rails_db/shared/data_table', table: table,
                                            header: options[:header],
                                            footer: options[:footer],
                                            style:  options[:style]
    end

    def rails_db_data_table_sql(sql, options = {})
      options.reverse_merge!(
        style: :default,
        header: true,
        footer: false,
      )
      sql        = "#{sql}".strip
      sql_query  = RailsDb::SqlQuery.new(sql, false).execute

      render '/rails_db/shared/sql_result', sql_query: sql_query,
                                            header: options[:header],
                                            footer: options[:footer],
                                            style:  options[:style]
    end

    def rails_db_table_style(tag, style)
      style = STYLES[style] || STYLES[:default]
      style[tag.to_sym]
    end

  end
end

app/helpers/rails_db/tables_helper.rb
module RailsDb
  module TablesHelper

    def format_value(column, value)
      return value
      # TODO here
      return nil unless value
      case column.type
      when :datetime
        I18n.l(DateTime.parse(value), format: :long)
      when :date
        I18n.l(Date.parse(value), format: :long)
      else
        value
      end
    end

    def titleize_column(column, title = nil)
      column
    end

    def select_top_from_table(table)
      link_to raw("#{fa_icon('database')} SQL Query"), rails_db.sql_path(sql: "select * from #{table} limit 10")
    end

    def delete_row_path(table, record)
      options = params.permit!
      table_destroy_path(table,
        pk_id: record[table.primary_key],
        page: options[:page],
        q: options[:q])
    end

    def table_pagination_path
      params.delete(:pk_id)
      params_to_hash params.merge({action: :data})
    end

    def column_is_checked?(table_name, column_name)
      if cookies["Table: #{table_name}"].present?
        !cookies["Table: #{table_name}"].split(',').include?(column_name)
      else
        true
      end
    end

    def display_style_column(table_name, column_name)
      column_is_checked?(table_name, column_name) ? 'display' : 'display:none'
    end

    def search_form_class
      hash = params.permit!.to_hash.fetch('q', {})
      keys = hash.keys
      return 'hide' if keys.empty?
      return 'hide' if keys == ['s']
      nil
    end

  end
end

app/views/rails_db/sql/_explain.html.erb
<div id="explain_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Explain SQL</h2>
  <p class="lead"><%= sql %></p>
  <pre>
    <% sql_query.explain.rows.each do |row| %>
      <%= row.join(' ') %>
    <% end %>
  </pre>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/rails_db/sql/_history.html.erb
<div id="history_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">History</h2>
  <div class='scrollable sql_history_items'>
    <% RailsDb::History.history.each do |sql| %>
      <p>
        <%= link_to sql_execute_path(sql: sql), method: :post do %>
          <%= fa_icon 'bars' %>
          <%= sql %>
        <% end %>
      </p>
    <% end %>
    <% if RailsDb::History.history.empty? %>
      Nothing yet.
    <% end %>
  </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/rails_db/sql/_import_sample.html.erb
<div id="sample_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Sample</h2>
  <div class='scrollable sql_history_items'>
    <pre>
      update users set email = 'e1@e.com' where id = 5;
      update users set email = 'e2@e.com' where id = 6;
      update users set email = 'e3@e.com' where id = 7;

      CREATE TABLE MyGuests (
        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        firstname VARCHAR(30) NOT NULL,
        lastname VARCHAR(30) NOT NULL,
        email VARCHAR(50),
        reg_date TIMESTAMP
      );
    </pre>
  </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/rails_db/sql/_results.html.erb
<% if sql_query.data.count > 0 %>
  <div class="large-11">
    <h4>Results</h4>
    <p>
      <span class="radius success label">Total: <%= pluralize sql_query.data.count, 'record' %></span>
      <span class="radius info label">Time: <%= sql_query.data.time %> seconds</span>
      <span class="radius secondary label"><a href="#" data-reveal-id="explain_modal" id='explain_modal_link'>Explain</a></span>
      <span class="radius warning label"><%= link_to raw("#{fa_icon('file-text-o')} Export to CSV"), sql_csv_path(sql: sql, format: 'csv'), method: :post %></span>
      <% if defined? Axlsx %>
        <span class="radius warning label"><%= link_to raw("#{fa_icon('file-excel-o')} Export to Excel"), sql_xls_path(sql: sql, format: 'xls'), method: :post %></span>
      <% end %>
    </p>
    <hr>
    <%= render 'explain', sql_query: sql_query, sql: sql %>
    <div class='scrollable'>
      <table>
        <thead>
          <tr>
            <% sql_query.data.columns.each do |column| %>
              <th><%= titleize_column(column) %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% sql_query.data.rows.each do |row| %>
            <tr>
              <% row.each do |item| %>
                <td class='query_result'><%= item %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
        <% if sql_query.data.count > 10 %>
          <tfoot>
            <tr>
              <% sql_query.data.columns.each do |column| %>
                <th><%= titleize_column(column) %></th>
              <% end %>
            </tr>
          </tfoot>
        <% end %>
      </table>
    </div>
  </div>
<% else %>
  <p>
    <span class="radius success label">SQL command successfully executed</span>
    <span class="radius info label">Time: <%= sql_query.data.time %> seconds</span>
    <span class="radius secondary label"><a href="#" data-reveal-id="explain_modal" id='explain_modal_link'>Explain</a></span>
  </p>
  <%= render 'explain', sql_query: sql_query, sql: sql %>
<% end %>

app/views/rails_db/sql/import.html.erb
<% title "SQL Import" %>

<%= form_tag :sql_start_import, multipart: true do %>
  <h3>Import SQL File</h3>

  <div class="large-11">
    <label>
      File
      <%= file_field_tag :file %>
    </label>
  </div>

  <div class="large-11">
    <p><span class="radius secondary label">* <%= RailsDb::Adapters::BaseAdapter::MULTI_STATEMENT_HELP_TEXT %></span></p>
    <%= submit_tag raw("&rarr; Import"), class: 'button small' %>
    &nbsp;
    &mdash;
    &nbsp;
    <a href="#" data-reveal-id="sample_modal" id='sample_modal_link'><%= fa_icon('bars') %> Sample</a></span>
    <%= render 'import_sample' %>
  </div>

  <% if @importer && @importer.result.ok? %>
    <div class="large-11">
      <h4>Results</h4>
      <p>
        <span class="radius success label">File was successfully imported</span>
        <span class="radius info label">Time: <%= @importer.time %> seconds</span>
      </p>
    </div>
  <% end %>

<% end %>

app/views/rails_db/sql/index.html.erb
<% title "SQL Editor" %>

<%= form_tag :sql_execute do %>

  <div class="large-12">
    <div class='left'>
      <h3>Execute SQL</h3>
    </div>

    <div class='left sql_exp_col'>
      <%= render '/rails_db/shared/exp_col' %>
    </div>
  </div>

  <div class='clear'></div>

  <% if @sql_query.valid? %>
    <% if @sql_query.data.is_error? %>
      <div class="large-12">
        <div class='alert-box alert'>
          <%= @sql_query.data.error.message %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="large-12">
    <textarea name='sql' id="sql" cols="120" rows="60"><%= @sql %></textarea>
  </div>

  <div class="large-12">
    <div class='panel execute_panel'>
      <p>
        <span class="radius secondary label">* be careful with your SQL. You may corrupt your DB. Make sure you have DB backup if making modifications.</span>
        <br/>
        <span class="radius secondary label">** you can autocomplete your SQL (Esc, Ctrl-Space or Ctrl)</span>
      </p>
      <%= submit_tag raw("&rarr; Execute"), class: 'button small' %>
      &nbsp;
      &mdash;
      &nbsp;
      <%= link_to raw("#{fa_icon('undo')} Reset"), :sql, data: {confirm: "Are you sure?"}, confirm: "Are you sure?" %>
      &nbsp;
      &mdash;
      &nbsp;
      <a href="#" data-reveal-id="history_modal" id='history_modal_link'><%= fa_icon('bars') %> History</a></span>
      <%= render 'history' %>
    </div>
  </div>

<% end %>

<% if @sql_query.valid? %>
  <%= render 'results', sql_query: @sql_query, sql: @sql %>
<% end %>

<script type="text/javascript">
  window.onload = function() {
    init_sql_editor("<%= RailsDb::Database.adapter.mime %>", <%= raw db_hint_options.to_json %>);
  };
</script>