config/routes.rb
RailsDb::Engine.routes.draw do
  root :to => 'dashboard#index'

  resources :tables, :only => [:index, :show] do
    get 'data'
    get 'csv'
    get 'truncate'
    get 'destroy' # to handle opens in new window (GET)
    get 'edit'    # to handle opens in new window (GET)
    put 'update'  # to handle opens in new window (GET)
    get 'xlsx'
    get 'new'
    post 'create'
  end

  get '/sql' => 'sql#index', as: :sql
  get '/import' => 'sql#import', as: :sql_import

  post '/execute' => 'sql#execute', as: :sql_execute
  post '/sql-csv' => 'sql#csv', as: :sql_csv
  post '/sql-xls' => 'sql#xls', as: :sql_xls
  post '/import-start' => 'sql#import_start', as: :sql_start_import

  get '/data-table' => 'dashboard#data_table', as: :data_table
  get '/standalone' => 'dashboard#standalone', as: :standalone
end

if RailsDb.automatic_routes_mount
  Rails.application.routes.draw do
    mount_rails_db_routes
  end
end

app/controllers/rails_db/application_controller.rb
module RailsDb
  class ApplicationController < ActionController::Base
    helper :all
    helper_method :per_page

    before_action :verify_access
    before_action :set_abstract_model_class

    if RailsDb.http_basic_authentication_enabled
      http_basic_authenticate_with name: RailsDb.http_basic_authentication_user_name,
                                   password: RailsDb.http_basic_authentication_password
    end

    private

    def verify_access
      result = RailsDb.verify_access_proc.call(self)
      redirect_to('/', error: 'Access Denied', status: 401) unless result
    end

    def per_page
      params[:per_page] || session[:per_page]
    end

    def set_abstract_model_class
      return unless params[:abstract_model_class].present?

      if (found = RailsDb.available_abstract_model_classes.find { |klass| klass.name == params[:abstract_model_class] })
        RailsDb.abstract_model_class = found
      end
    end
  end
end

app/controllers/rails_db/dashboard_controller.rb
module RailsDb
  class DashboardController < RailsDb::ApplicationController

    def index
    end

  end
end

app/controllers/rails_db/sql_controller.rb
module RailsDb
  class SqlController < RailsDb::ApplicationController
    before_action :load_query, only: [:index, :execute, :csv, :xls]

    def index
    end

    def execute
      render :index
    end

    def csv
      send_data(@sql_query.to_csv, type: 'text/csv; charset=utf-8; header=present', filename: 'results.csv')
    end

    def xls
      render xlsx: 'xls', filename: 'results.xlsx'
    end

    def import
    end

    def import_start
      @importer = SqlImport.new(params[:file])
      result    = @importer.import
      if result.ok?
        flash[:notice] = 'File was successfully imported'
      else
        flash[:alert] = "Error occurred during import: #{result.error.message}"
      end
      render :import
    end

    private

    def load_query
      @sql       = "#{params[:sql]}".strip
      @sql_query = RailsDb::SqlQuery.new(@sql).execute
    end

  end
end

app/controllers/rails_db/tables_controller.rb
module RailsDb
  class TablesController < RailsDb::ApplicationController
    LOAD_TABLE_ACTIONS = [:show, :data, :csv, :truncate, :destroy, :edit, :update, :xlsx, :new, :create]

    before_action :find_table, only: LOAD_TABLE_ACTIONS

    def index
      @tables = RailsDb::Database.accessible_tables
    end

    def show
    end

    def new
      @record = model.new
    end

    def create
      unless RailsDb.sandbox
        @record = model.new(record_attributes)
        @record.save!
      end

      build_search
      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    def data
      session[:per_page] = per_page
      build_search
      respond_to do |page|
        page.html {}
        page.js {}
      end
    end

    def csv
      send_data(@table.to_csv, type: 'text/csv; charset=utf-8; header=present', filename: "#{@table.name}.csv")
    end

    def xlsx
      if defined? Axlsx
        render xlsx: 'table', filename: "#{@table.name}.xlsx"
      else
        raise 'RailsDb could not find Axlsx, please add it to your Gemfile: "gem \'caxlsx_rails\'"'
      end
    end

    def truncate
      unless RailsDb.sandbox
        @table.truncate
      end
      render :data
    end

    def destroy
      build_search

      unless RailsDb.sandbox
        @table.delete(params[:pk_id])
      end

      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    def edit
      @record = @table.as_model.find(params[:pk_id])
      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    def update
      @record = @table.as_model.find(params[:pk_id])

      unless RailsDb.sandbox
        @record.update(record_attributes)
      end

      respond_to do |page|
        page.html { redirect_to action: :data, table_id: params[:table_id] }
        page.js {}
      end
    end

    private

    def build_search
      if Rails::VERSION::MAJOR >= 5
        search_params = params.dup.permit!.to_h.with_indifferent_access
      else
        search_params = params
      end
      @q       = model.ransack(search_params[:q])
      @sql     = @q.result.page(params[:page]).per(per_page).to_sql
      @records = @q.result.page(params[:page]).per(per_page)
      @q.build_condition if @q.conditions.empty?
      @q.build_sort      if @q.sorts.empty?
    end

    def model
      @model ||= @table.as_model
    end

    def record_attributes
      params[:record].permit!
    end

    def find_table
      @table ||= RailsDb::Table.new(params[:id] || params[:table_id])
    end

  end
end

app/helpers/rails_db/application_helper.rb
module RailsDb
  module ApplicationHelper

    def rails_db
      super
    rescue NameError
      guess_name(request.path.split('/').reject(&:blank?))
    end

    # in case engine was added in namespace
    def guess_name(sections)
      if sections.size > 1
        sections[-1] = 'rails_db'
        variable     = sections.join("_")
        result       = eval(variable)
      end
    rescue NameError
      sections.delete_at(-2)
      guess_name(sections)
    end

    def rails_db_tables
      RailsDb::Database.accessible_tables
    end

    def link_to_add_fields(name, f, type)
      new_object = f.object.send "build_#{type}"
      id = "new_#{type}"
      fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
        render(type.to_s + "_fields", f: builder)
      end
      link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end

    def sidebar_classes
      if show_sidebar?
        'large-3 large-pull-9 columns'
      else
        'large-3 large-pull-9 columns hide'
      end
    end

    def main_content_classes
      if show_sidebar?
        'large-9 push-3 columns collapsed'
      else
        'large-12 push-0 columns expanded'
      end
    end

    def show_sidebar?
      return true if controller_name == 'dashboard' && action_name == 'index'
      cookies['sidebar_hidden'] != 'true'
    end

    def title(str)
      content_for :title do
        raw("#{str}"[0].upcase + "#{str}"[1..-1])
      end
    end

    def fa_icon(icon_name)
      %{<i class="fa fa-#{icon_name}"></i>}.html_safe
    end

    def db_hint_options
      result = {}
      RailsDb::Database.accessible_tables.each do |table_name|
        result[table_name] = RailsDb::Table.new(table_name).columns.inject([]) {|res, e| res << e.name; res }
      end
      result
    end

    def params_to_hash(p)
      if p.respond_to?(:to_unsafe_h)
        p.to_unsafe_h
      else
        p
      end
    end

    def insert_css_file(file)
      if using_sprockets?
        # For Sprockets, use the asset pipeline
        # Remove .css extension and use the file path as-is for asset pipeline
        asset_name = file.gsub('.css', '')
        stylesheet_link_tag asset_name, media: "all"
      else
        # For Propshaft/Rails 8 compatibility - inline the CSS
        css_path = File.expand_path(File.dirname(__FILE__) + "/../../assets/stylesheets/#{file}")
        if File.exist?(css_path)
          raw "<style>#{File.read(css_path)}</style>"
        else
          ""
        end
      end
    end

    def insert_js_file(file)
      if using_sprockets?
        # For Sprockets, use the asset pipeline
        # Remove .js extension and use the file path as-is for asset pipeline
        asset_name = file.gsub('.js', '')
        javascript_include_tag asset_name
      else
        # For Propshaft/Rails 8 compatibility - inline the JavaScript
        js_path = File.expand_path(File.dirname(__FILE__) + "/../../assets/javascripts/#{file}")
        if File.exist?(js_path)
          raw "<script>#{File.read(js_path)}</script>"
        else
          ""
        end
      end
    end

    private

    def using_sprockets?
      # Check if sprockets-rails is available and being used
      return false unless defined?(Sprockets)
      
      # Check if Rails.application.assets is a Sprockets environment
      Rails.application.assets.is_a?(Sprockets::Environment) ||
      Rails.application.assets.is_a?(Sprockets::Index)
    rescue
      # If anything fails, assume we're not using Sprockets
      false
    end
  end
end

app/helpers/rails_db/flash_messages_helper.rb
module RailsDb
  module FlashMessagesHelper
    # <div class="alert-box [success alert secondary]">
    #   This is an alert box.
    #   <a href="" class="close">&times;</a>
    # </div>
    DEFAULT_KEY_MATCHING = {
      :alert     => :alert,
      :notice    => :success,
      :info      => :info,
      :secondary => :secondary,
      :success   => :success,
      :error     => :alert,
      :warning   => :warning
    }
    def display_flash_messages(key_matching = {})
      key_matching = DEFAULT_KEY_MATCHING.merge(key_matching)
      key_matching.default = :standard

      result = capture do
        flash.each do |key, value|
          alert_class = key_matching[key.to_sym]
          concat alert_box(value, alert_class)
        end
      end
      flash.clear
      result
    end

  private

    def alert_box(value, alert_class)
      content_tag :div, data: { alert: '' }, class: "alert-box #{alert_class}" do
        concat value
        concat close_link
      end
    end

    def close_link
      link_to("&times;".html_safe, '#', class: :close)
    end

  end
end

app/helpers/rails_db/rails_db_data_table_helper.rb
module RailsDb
  module RailsDbDataTableHelper
    # TODO check styles
    STYLES = {
      default: {
        table: 'table',
        tr: 'table_tr',
        th: 'table_th',
        td: 'table_td',
        thead: 'table_thead',
        tfoot: 'table_tfoot'
      },
      bootstrap: {
        table: 'table table-bordered table-striped table-hover',
        tr: 'table_tr',
        th: 'table_th',
        td: 'table_td',
        thead: 'table_thead',
        tfoot: 'table_tfoot'
      },
      foundation: {
        table: 'table',
        tr: 'table_tr',
        th: 'table_th',
        td: 'table_td',
        thead: 'table_thead',
        tfoot: 'table_tfoot'
      }
    }

    def rails_db_data_table(table_name, options = {})
      options.reverse_merge!(
        style: :default,
        header: true,
        footer: false,
        columns: [],
        limit: nil,
        order_by: nil,
        order: :asc
      )
      table = RailsDb::Table.new(table_name)
        .limit(options[:limit])
        .order_by(options[:order_by])
        .select(options[:columns])
        .order(options[:order])

      render '/rails_db/shared/data_table', table: table,
                                            header: options[:header],
                                            footer: options[:footer],
                                            style:  options[:style]
    end

    def rails_db_data_table_sql(sql, options = {})
      options.reverse_merge!(
        style: :default,
        header: true,
        footer: false,
      )
      sql        = "#{sql}".strip
      sql_query  = RailsDb::SqlQuery.new(sql, false).execute

      render '/rails_db/shared/sql_result', sql_query: sql_query,
                                            header: options[:header],
                                            footer: options[:footer],
                                            style:  options[:style]
    end

    def rails_db_table_style(tag, style)
      style = STYLES[style] || STYLES[:default]
      style[tag.to_sym]
    end

  end
end

app/helpers/rails_db/tables_helper.rb
module RailsDb
  module TablesHelper

    def format_value(column, value)
      return value
      # TODO here
      return nil unless value
      case column.type
      when :datetime
        I18n.l(DateTime.parse(value), format: :long)
      when :date
        I18n.l(Date.parse(value), format: :long)
      else
        value
      end
    end

    def titleize_column(column, title = nil)
      column
    end

    def select_top_from_table(table)
      link_to raw("#{fa_icon('database')} SQL Query"), rails_db.sql_path(sql: "select * from #{table} limit 10")
    end

    def delete_row_path(table, record)
      options = params.permit!
      table_destroy_path(table,
        pk_id: record[table.primary_key],
        page: options[:page],
        q: options[:q])
    end

    def table_pagination_path
      params.delete(:pk_id)
      params_to_hash params.merge({action: :data})
    end

    def column_is_checked?(table_name, column_name)
      if cookies["Table: #{table_name}"].present?
        !cookies["Table: #{table_name}"].split(',').include?(column_name)
      else
        true
      end
    end

    def display_style_column(table_name, column_name)
      column_is_checked?(table_name, column_name) ? 'display' : 'display:none'
    end

    def search_form_class
      hash = params.permit!.to_hash.fetch('q', {})
      keys = hash.keys
      return 'hide' if keys.empty?
      return 'hide' if keys == ['s']
      nil
    end

  end
end

app/views/rails_db/tables/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to raw("#{fa_icon 'minus'} remove"), '#', class: "remove_fields" %>
</div>

app/views/rails_db/tables/_data.html.erb
<% title "\"#{@table.name}\" Data"%>

<h2 class='left'>Table: <%= @table.name %></h2>
<div class='right'>
  <%= link_to '+ ADD', table_new_path(@table), remote: true, class: 'button small' %>
</div>

<div class='clear'></div>

<hr/>

<dl class="sub-nav">
  <dd><%= render '/rails_db/shared/exp_col' %></dd>
  <dd class="active"><%= link_to raw("#{fa_icon('table')} Records"), table_data_path(@table), remote: true %></dd>
  <dd><%= link_to raw("#{fa_icon('tasks')} Schema"), table_path(@table), remote: true %></dd>
  <dd><%= select_top_from_table(@table.name) %></dd>
  <dd>
    <a href="#" data-options="align: bottom" data-dropdown="download-files"><%= fa_icon 'download' %> Export</a>
  </dd>
  <dd>
    <a href="#" data-options="align: bottom" data-dropdown="drop"><%= fa_icon 'th-large' %> Functions</a>
  </dd>
  <dd class="right"><%= link_to raw("#{fa_icon('cogs')} Settings"), '#', :class => 'settings-link', :table_name => "#{@table.name}" %></dd>
  <dd class="right"><%= link_to raw("#{fa_icon('search')} Search"), '#', :class => 'search-link' %></dd>
</dl>
<div class="clearfix"></div>

<ul id="drop" class="f-dropdown" data-dropdown-content>
  <li><%= link_to raw("#{fa_icon('trash-o')} Truncate Table"), table_truncate_path(@table), data: {confirm: 'Are you sure?'} %></li>
</ul>

<ul id="download-files" class="f-dropdown" data-dropdown-content>
  <li><%= link_to raw("#{fa_icon('file-text-o')} Export table to CSV"), table_csv_path(@table) %></li>
  <% if defined? Axlsx %>
    <li><%= link_to raw("#{fa_icon('file-excel-o')} Export table to Excel"), table_xlsx_path(@table, format: 'xls') %></li>
  <% end %>
</ul>

<div class='scrollable'>
  <%= search_form_for @q, url: table_data_path(@table), method: :get, remote: true, html: { id: 'search_form', class: search_form_class } do |f| %>
    <div class='panel no_bottom_padding'>
      <h6>Search</h6>
      <%= f.condition_fields do |c| %>
        <%= render "condition_fields", f: c %>
      <% end %>
      <p><%= link_to_add_fields raw("#{fa_icon 'plus'} Add Conditions"), f, :condition %></p>
      <div class="field sorting_options">
        Sort:
        <%= f.sort_fields do |s| %>
          <%= s.sort_select %>
        <% end %>
      </div>
      <div class="actions"><%= f.submit "Search", class: 'button small' %></div>
    </div>
  <% end %>

  <div class='rails-db-settings panel no_bottom_padding' style="display:none">
    <h6>Settings</h6>
    <% @table.columns.each do |column| %>
      <label class='column-name'>
        <%= check_box_tag(column.name, nil, column_is_checked?(@table.name, column.name), class: "#{column.name}") %>
        <%= column.name %>
      </label>
    <% end %>
    <div class='clearfix'></div>
  </div>

  <table id="search_records" class='table'>
    <thead>
      <tr>
        <% if @table.primary_key %>
          <th colspan="2">Actions</th>
        <% end %>
        <% @model.column_names.each do |column| %>
          <th class="column_<%= column %>" style="<%= display_style_column(@table.name, column)%>">
            <%= sort_link @q, column, column, controller: :tables, action: :data %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr class="row_<%= record[@table.primary_key] %>">
          <%= render 'row', record: record %>
        </tr>
      <% end %>

      <% if @records.none? %>
        <td>No Records</td>
      <% end %>
    </tbody>

    <% if @records.size > 10 %>
      <tfoot>
        <tr>
          <% if @table.primary_key %>
            <th colspan="2">Actions</th>
          <% end %>
          <% @model.column_names.each do |column| %>
            <th> <%= sort_link @q, column, column, controller: :tables, action: :data %> </th>
          <% end %>
        </tr>
      </tfoot>
    <% end %>
  </table>
</div>

<p>
  <span class="radius success label">Total: <%= pluralize @records.total_count, 'record' %></span>
  <span class="radius secondary label"><a href="#" data-reveal-id="sql_modal" id='sql_modal_link'>SQL</a></span>
</p>

<% if @records.total_count > 10 %>
  <div class='left'>
    <%= form_tag table_pagination_path, method: :get, remote: true do %>
      <%= select_tag :per_page, options_for_select([10, 15, 20, 50, 100, 200, 500], per_page), class: 'per_page_pagination_select' %>
    <% end %>
  </div>

  <div class='left per_page_pagination'>
    <%= paginate @records, remote: true, params: { controller: :tables, action: :data } %>
  </div>
<% end %>

<div class='clear'></div>

<%= render 'sql', sql: @sql %>

app/views/rails_db/tables/_edit_row.html.erb
<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="false" role="dialog">
  <%= form_tag(table_update_row_path(@table), method: "get", remote: true) do %>
    <% table_data.each_pair do |key, val| %>
      <% if key == @table.primary_key %>
        <%= hidden_field_tag key, val %>
      <% else %>
        <%= label_tag key %>
        <%= text_field_tag key, val %>
      <% end %>
    <% end %>
    <%= submit_tag("Edit", class: 'button') %>
    <%= link_to 'Cancel', '#', class: "close-modal" %>
  <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/rails_db/tables/_new.html.erb
<a class="close-reveal-modal" aria-label="Close">&#215;</a>

<h2 id="modalTitle">New</h2>

<%= simple_form_for @record, as: 'record', url: table_create_path(@table, pk_id: @record[@table.primary_key]), remote: true, method: :post, html: {class: 'vertical_form'} do |form| %>
    <div class='scrollable_form'>
      <% @record.class.columns.each do |column| %>
        <% name = column.name %>
        <% next if [@table.primary_key, 'created_at', 'updated_at'].include?(column.name) %>
        <% if name.to_s == "country" %>
          <%= form.input name, label: name, as: :string %>
        <% else %>
          <%= form.input name, label: name %>
        <% end %>
      <% end %>
    </div>
    <%= form.submit 'SAVE', class: 'button small' %>
    <a class='close' onclick="$('#system_modal').foundation('reveal', 'close');$">Close</a>
<% end %>

<span class="radius warning label">NOTE: Update will happen without any validations.</span>

app/views/rails_db/tables/_row.html.erb
<% if @table.primary_key.present? %>
  <td>
    <%= link_to fa_icon('minus-circle'), delete_row_path(@table, record), :class => 'red', remote: true, title: 'Delete Record', confirm: 'Are you sure you want to delete this record?', data: {confirm: 'Are you sure you want to delete this record?'} %>
  </td>
  <td>
    <%= link_to fa_icon('pencil-square'), table_edit_path(@table, pk_id: record[@table.primary_key]), :class => 'yellow', remote: true, title: 'Edit Record' %>
  </td>
<% end %>

<% @table.columns.each do |column| %>
  <td class="column_<%= column.name %>" style=<%= display_style_column(@table.name, column.name) %>>
    <% name = column.name %>
    <%= format_value(column, record[name]) %>
  </td>
<% end %>

app/views/rails_db/tables/_search.html.erb
<% title "\"#{@table.name}\" Search"%>

<h2>Table: <%= @table.name %></h2>

<div class='clear'></div>

<hr/>

<dl class="sub-nav">
  <dd><%= render '/rails_db/shared/exp_col' %></dd>
  <dd class="active"><%= link_to raw("#{fa_icon('table')} Records"), table_data_path(@table), remote: true %></dd>
  <dd><%= link_to raw("#{fa_icon('tasks')} Schema"), table_path(@table), remote: true %></dd>
  <dd><%= select_top_from_table(@table.name) %></dd>
  <dd>
    <a href="#" data-options="align: bottom" data-dropdown="download-files"><%= fa_icon 'download' %> Export</a>
  </dd>
  <dd>
    <a href="#" data-options="align: bottom" data-dropdown="drop"><%= fa_icon 'th-large' %> Functions</a>
  </dd>
  <dd class="right"><%= link_to raw("#{fa_icon('cogs')} Settings"), '#', :class => 'settings-link', :table_name => "#{@table.name}" %></dd>
  <dd class="right"><%= link_to raw("#{fa_icon('search')} Search"), '#', :class => 'search-link' %></dd>
</dl>
<div class="clearfix"></div>

<ul id="drop" class="f-dropdown" data-dropdown-content>
  <li><%= link_to raw("#{fa_icon('trash-o')} Truncate Table"), table_truncate_path(@table), data: {confirm: 'Are you sure?'} %></li>
</ul>

<ul id="download-files" class="f-dropdown" data-dropdown-content>
  <li><%= link_to raw("#{fa_icon('file-text-o')} Export to CSV"), table_csv_path(@table) %></li>
  <% if defined? Axlsx %>
    <li><%= link_to raw("#{fa_icon('file-excel-o')} Export to Excel"), table_xlsx_path(@table, format: 'xls') %></li>
  <% end %>
</ul>

<%= search_form_for @q, url: table_search_path(@table), method: :get, remote: true, html: { id: 'search_form', class: search_form_class } do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields raw("#{fa_icon 'plus'} Add Conditions"), f, :condition %></p>
  <div class="field sorting_options">
    Sort:
    <%= f.sort_fields do |s| %>
      <%= s.sort_select %>
    <% end %>
  </div>
  <div class="actions"><%= f.submit "Search", class: 'button small' %></div>
<% end %>

<div class='scrollable'>
  <table id="search_records" class='table'>
    <thead>
      <tr>
        <% if @table.primary_key %>
          <th colspan="2">Actions</th>
        <% end %>
        <% @model.column_names.each do |column| %>
          <th> <%= sort_link(@q, column, column) %> </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr class="row_<%= record[@table.primary_key] %>">
          <%= render 'row', record: record %>
        </tr>
      <% end %>

      <% if @records.none? %>
        <td>No Records</td>
      <% end %>
    </tbody>
  </table>
</div>

<p>
  <%= paginate @records, remote: true %>
</p>

app/views/rails_db/tables/_show.html.erb
<% title "\"#{@table.name}\" Schema"%>

<h2>Table: <%= @table.name %></h2>

<hr/>

<dl class="sub-nav">
  <dd><%= render '/rails_db/shared/exp_col' %></dd>
  <dd><%= link_to raw("#{fa_icon('table')} Records"), table_data_path(@table), remote: true %></dd>
  <dd class="active"><%= link_to raw("#{fa_icon('tasks')} Schema"), table_path(@table), remote: true %></dd>
  <dd><%= select_top_from_table(@table.name) %></dd>
  <dd>
    <a href="#" data-options="align: bottom" data-dropdown="download-files"><%= fa_icon 'download' %> Export</a>
  </dd>
  <dd>
    <a href="#" data-options="align: bottom" data-dropdown="drop"><%= fa_icon 'th-large' %> Functions</a>
  </dd>
</dl>

<ul id="download-files" class="f-dropdown" data-dropdown-content>
  <li><%= link_to raw("#{fa_icon('file-text-o')} Export table to CSV"), table_csv_path(@table) %></li>
  <% if defined? Axlsx %>
    <li><%= link_to raw("#{fa_icon('file-excel-o')} Export table to Excel"), table_xlsx_path(@table, format: 'xls') %></li>
  <% end %>
</ul>

<ul id="drop" class="f-dropdown" data-dropdown-content>
  <li><%= link_to raw("#{fa_icon('trash-o')} Truncate Table"), table_truncate_path(@table), remote: true, confirm: 'Are you sure?', data: {confirm: 'Are you sure?'} %></a></li>
</ul>

<h3>Schema</h3>

<table>
  <thead>
    <tr>
      <% if @table.primary_key.present? %>
        <th>PK</th>
      <% end %>
      <% @table.column_properties.each do |key| %>
        <th><%= key.titleize.upcase %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @table.columns.each do |col| %>
      <tr>
        <% if @table.primary_key %>
          <% if @table.primary_key == col.name %>
            <td>
              <span class='pk'><%= fa_icon 'key' %></span>
            </td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>

        <% @table.column_properties.each do |key| %>
          <td class="<%= key %>">
            <% value = col.send(key) %>
            <%= value %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<h3>Indexes</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unique</th>
      <th>Columns</th>
      <th>Length</th>
      <th>Orders</th>
      <th>Where</th>
      <th>Type</th>
      <th>Using</th>
    </tr>
  </thead>
  <tbody>
    <% @table.indexes.each do |index| %>
     <tr>
      <td><%= index.name %></td>
      <td><%= index.unique %></td>
      <td><%= index.columns %></td>
      <td><%= index.lengths %></td>
      <td><%= index.orders %></td>
      <td><%= index.where %></td>
      <td><%= index.type %></td>
      <td><%= index.using %></td>
     </tr>
    <% end %>
    <% if @table.indexes.none? %>
      <tr><td colspan='7'>No Indexes</td></tr>
    <% end %>
  </tbody>
</table>

app/views/rails_db/tables/_sql.html.erb
<div id="sql_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">SQL</h2>
  <pre>
    <%= sql %>
  </pre>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/rails_db/tables/data.html.erb
<%= render 'data' %>

app/views/rails_db/tables/show.html.erb
<%= render 'show' %>